.eslintrc.json, app/login/layout.tsx, app/login/page.tsx, components/common/Input.tsx, components/login/LoginForm.tsx, components/login/LoginHeader.tsx
feat/login -> dev
login layout, form 추가
react-hook-form controller 적용
=> Feature/login add layout, form 

components/auth/AuthInput.tsx, components/auth/LoginForm.tsx, components/auth/RegisterForm.tsx, services/auth.ts, stores/authStore.ts, tsconfig.json
feat/login -> dev
로그인 기능 + 토큰 zustand Store 저장 기능 추가
=> Feature/add login, authStore

declarations.d.ts, next.config.mjs, svgr.d.ts, tsconfig.json
- svgr의 설정을 next의 공식적인 방식으로 변경하였고 타입정의 또한 수정하였습니다.
- https://react-svgr.com/docs/next/
=> Fix: svgr의 설정 변경

app/mypage/layout.tsx, app/mypage/page.tsx, components/landing/Footer.tsx, components/landing/Header.tsx, components/nav/DashboardNav.tsx, components/nav/LandingNav.tsx, components/nav/MyNav.tsx, public/images/MainImage.svg
ex) feat/landing -> dev
Image 태그들에 svgr을 적용하였습니다.
내부 페이지는 App Router를, 외부 페이지는 Link를 통해 연결했습니다.
중복되어있던 컴포넌트명을 수정했습니다.(Dashboard.tsx의 컴포넌트명 MyNav -> DashBoardNav)
=> 이미지 컴포넌트화, AppRouter구현, 컴포넌트명 수정

app/not-found.tsx
커스텀 404페이지를 제작하여 개발모드 실행시 토스티파이 에러가 나는 현상이 해결되는지 테스트를 해보았습니다. 일단 제 실행환경에선 더이상 에러메세지가 나오지 않는 것으로 확인했습니다.
=> Feat: 404페이지 제작

.env, app/api/login/route.ts, app/globals.css, app/layout.tsx, app/login/page.tsx, app/mydashboard/layout.tsx, app/mydashboard/page.tsx, components/DashboardList.tsx, components/auth/LoginForm.tsx, components/common/ToastProvider.tsx, components/nav/LandingNav.tsx, services/auth.ts, types/user/dashboard.ts, utils/axios.ts
- 나의 대시보드 페이지에서 서버에서 데이터 페칭후 클라이언트 컴포넌트에서 렌더링하는 로직을 구현
=> Feature: 나의 대시보드 데이터 페칭 구현

components/auth/Input.tsx, components/auth/LoginForm.tsx, components/auth/RegisterForm.tsx, services/auth.ts, services/users.ts
feat/login -> dev
useAuthStore 새로고침시 초기화 문제 persist 사용하여 sessionStorage 처리
registerForm use client 누락 추가
=> feat: add persist middleware

components/auth/Input.tsx, components/auth/LoginForm.tsx, components/auth/RegisterForm.tsx, services/auth.ts, services/users.ts
=> Revert "Revert "feat: add persist middleware""

app/api/login/route.ts, components/auth/LoginForm.tsx, middleware.ts, stores/authStore.ts, utils/axiosServer.ts
feat/services -> dev
쿠키 확인 미들웨어 추가
=> feat: 인증 확인 middleware 추가

middleware.ts, tailwind.config.ts
feat/services -> dev
tailwind 브레이크 포인트 추가
=> feat: add custom screen breakpoints to Tailwind CSS

app/(dashboard)/dashboard/[dashboardId]/page.tsx, app/(dashboard)/mydashboard/page.tsx, components/Modal/components/ModalOpenButton.tsx, components/Modal/views/DashboardAddForm.tsx, components/dashboard/Column.tsx, components/dashboard/DashboardsField/MyDashboards.tsx, components/dashboard/DashboardsField/index.tsx, components/dashboard/InviteField/InvitedDashboards.tsx, components/dashboard/InviteField/InvitedTable.tsx, components/dashboard/InviteField/index.tsx, services/client/dashboards.ts, services/common.ts
- React의 Suspense를 사용하여 병렬 요청을 구현했습니다.
- 위의 작업을 위해 폴더 구조가 변경되었습니다.
- 나머지는 코드단에 설명 적어두겠습니다!
=> Feat: 나의 대시보드 로직 구현 완료

components/dashboard/Column.tsx, components/dashboard/Content.tsx
feat/dashboard -> dev
모달 버튼 변경
=> feat: modal button change

components/myPage/Password/PasswordChangeForm.tsx, constants/formOption.ts
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
=> 비밀번호 변경 폼 수정

components/Modal/views/InviteForm.tsx, components/nav/DashboardNav.tsx
ex) feat/login -> dev
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
=> 초대하기 기능 구현

app/api/logout/route.ts
feat/services -> dev
쿠키 삭제 api 추가 (로그아웃용)
=> feat: add clear cookie api

app/api/login/route.ts
feat/login -> dev
로그인 api responese에 누락된 user 추가
=> fix: add user to login api response

components/nav/DashboardNav.tsx, components/nav/InviteeImage.tsx
ex) feature-nav-> dev
ex) 현재 대시보드에 초대받은 사람들의 이미지를 보여줍니다.
=> 현재 대시보드에 참여하고 있는 사람들의 이미지 보여주기

components/nav/DashboardNav.tsx, components/nav/MembersProfile.tsx
ex) feat/login -> dev
참여 멤버가 일정 수 이상일 때는 숫자로 표기
=> 참여 멤버가 일정 수 이상일 때는 숫자로 표기

app/(dashboard)/dashboard/[dashboardId]/page.tsx, components/Modal/components/ModalImageInput.tsx, components/Modal/views/ColumnAddForm.tsx, components/Modal/views/ModalColumnCard.tsx, components/Modal/views/ToDoEditForm.tsx, components/dashboard/Card.tsx, components/dashboard/Column.tsx, components/dashboard/Content.tsx, contexts/DashboardContext.tsx, services/client/cards.ts, services/common.ts, types/user/column.ts
=> feat: add update cards

app/mypage/page.tsx, components/SideBar/SideBar.tsx, components/SideBar/SideBarItem.tsx, components/SideBar/SideBarList.tsx, components/nav/DashboardNav.tsx
=> 사이드 바 반응형 디자인 추가, 네비게이션 바 수정

components/myPage/Password/PasswordChangeForm.tsx
ex) feat/login -> dev
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
=> 비밀번호 변경 폼 반응형 디자인 변경

components/Modal/views/ToDoAddForm.tsx, components/Modal/views/ToDoEditForm.tsx
ex)
ex) 변경사항에서 에러 있을때 전송불가능하게 변경
=> feat : 에러기능추가
